### ISSUE TITLE
Unable to filter out certain exceptions from RollBar

### ISSUE THREAD

**Issue by SergioCursor** [newism/craft-rollbar#13]
Hey guys

Thanks for the plugin - very helpful!

Quick question - we have the need to be able to filter out certain exception types from being sent to RollBar. We find that our logs fill with TemplateNotFound Exceptions and would rather 404's were not sent to Rollbar.

Would it be possible to add a 'exceptions to ignore' setting or similar so that the plugin can check before sending an exception?

Thanks
Sergio

**Comment by leevigraham** [comment]
Merged https://github.com/newism/craft-rollbar/pull/14
