### ISSUE TITLE
PHP 7.4 - Failed to instantiate component or class "newism\rollbar\assetbundles\rollbar\RollbarAsset"

### ISSUE THREAD

**Issue by JonStonesCursor** [newism/craft-rollbar#15]
We're currently experiencing an issue when trying to use the Rollbar plugin on sites using PHP 7.4.
The error we're receiving is: 

Failed to instantiate component or class "newism\rollbar\assetbundles\rollbar\RollbarAsset".
Caused by: ReflectionException
Class newism\rollbar\assetbundles\rollbar\RollbarAsset does not exist

When using PHP 7.2 the issue doesn't seem to occur.

![Screenshot 2021-04-23 at 10 23 59](https://user-images.githubusercontent.com/77847068/115850937-51022000-a41e-11eb-88ae-d4f6fa478c89.png)

**Comment by leevigraham** [comment]
I'll check it out.

**Comment by leevigraham** [comment]
Can you try `dev-master` in your composer:

`"newism/craft-rollbar": "dev-master as 1.1.0"`
