### ISSUE TITLE
Craft v4

### ISSUE THREAD

**Issue by anchovy** [newism/craft-rollbar#19]
Hi, wondering if you are planning on updating this plugin for use on craft v4?

**Comment by leevigraham** [comment]
@anchovy Yep there is… we're trying to currently transfer ownership to another developer.

**Comment by anchovy** [comment]
Hi @leevigraham - any update on this?

**Comment by leevigraham** [comment]
@anchovy This repo is now archived. Consider https://plugins.craftcms.com/chrismou-rollbar as an alternative.
