### ISSUE TITLE
Create custom Target file.

### ISSUE THREAD

**Issue by RoussKS** [newism/craft-rollbar#3]
# Enhanchment
## This is part of the updates we're working on our fork.

If for some reason an exception occurs which is not handled by the Exception Handler this is not picked up and sent to Rollbar.

Instead it is only logged in Craft's log files (using Yii 2 FileTarget exception handler)

Solution: add new Target to Craft's logger dispatcher that captures logs of all categories

**Comment by RoussKS** [comment]
After an extra look and a bit of further research:

The current implementation relies on the Event dispatched by Craft's Web [ErrorHandler](https://github.com/craftcms/cms/blob/master/src/web/ErrorHandler.php)

As a result:
- It seems to be logging only exceptions from web requests that reach that part of the code
- It does not seem to log errors that happen on console commands
- It does not seem to log Queue errors as these are logged through `Craft:error()`
- It does not seem to log `Craft:error()` or `Craft::info()` messages which are effectively exceptions and messages handled by Craft itself or from similar logs from custom plugins. (in Craft 2, the rollbar plugin used to log those as well)

Thinking of a universal solution would be to replace the handler to be a custom `Target` (like FileTarget).
Feel free to share your thoughts on this as it is rather complicated

We can share an example

**Comment by leevigraham** [comment]
@RoussKS Long time but I've been looking into this again.

The only way I can see to catch all errors is to overwrite the [Yii error handler](https://www.yiiframework.com/doc/api/2.0/yii-web-errorhandler). Craft already does this for web exceptions but not console exceptions.

I've created a PR to cover this: https://github.com/craftcms/cms/pull/10006

I'm pretty sure this will also cover Queue errors as they run through the console.

**Comment by RoussKS** [comment]
Thanks @leevigraham . Sounds reasonable so feel free to close this issue.

**Comment by leevigraham** [comment]
@RoussKS I also looked at a Target but I think you only get the message… not the full exception object.
