### ISSUE TITLE
Add setting for enabled/disabled server & client logging

### ISSUE THREAD

**Issue by RoussKS** [newism/craft-rollbar#4]
# Enhanchment

Understanding that the plugin itself checks whether a variable is provided for logging, having a lightswitch setting makes it easy to enable/disable logging if for some reason we want to temporarily postpone logging without removing the keys.

Example use, local development, xdebug & rollbar don't really work well together when exceptions occur due to nested loops. Only one can be active.

Not sure if you want such feature as it is more of a commodity and prefer keep the simple checking of tokens present.

**Comment by zizther** [comment]
It would be great to have a setting/config to turn this on or offer per env

**Comment by leevigraham** [comment]
A config for this would be good to add to make it clear.

You can achieve the same thing by setting the accessToken to false or an empty string.

https://github.com/newism/craft-rollbar/blob/master/src/controllers/AdminController.php#L22-L31

**Comment by RoussKS** [comment]
@leevigraham good point that accessToken achieve the same, but isn't .env param taking precedence over a the admin config?
Hence having a lightswitch controllable via admin allows for quick setting keeping the accessToken untouched?

**Comment by leevigraham** [comment]
This repo is now archived. Consider https://plugins.craftcms.com/chrismou-rollbar as an alternative.
