### ISSUE TITLE
Allow inclusion of Rollbar's jQuery Plugin

### ISSUE THREAD

**Issue by RoussKS** [newism/craft-rollbar#7]
# Enhanchment
## This is part of the updates we're working on our fork.

Provide the option to load [Rollbar's jQuery plugin](https://docs.rollbar.com/docs/rollbarjs-plugins#section-j-query) in the templates

**Comment by leevigraham** [comment]
This repo is now archived. Consider https://plugins.craftcms.com/chrismou-rollbar as an alternative.
